version: '3.8'

services:

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        restart: always

    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: always

    db:
        image: postgres:15.1-alpine
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./data:/var/lib/postgresql/data/pgdata
        restart: on-failure

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            db:
              condition: service_started
        env_file:
            - .env
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=123456
        ports:
            - "5050:80"

    backend:
        build:
            context: ./backend
            dockerfile: backend.dockerfile
            target: prod
            args:
              GIT_TOKEN_PEDESIS: $GIT_TOKEN_PEDESIS
        depends_on:
            celery:
              condition: service_started
        env_file:
            - .env
        environment:
            - REDIS_HOST=redis
            - RABBITMQ_HOST=rabbitmq
            - POSTGRES_HOST=db
        volumes:
            - ./backend/app:/app
        ports:  
            - 5678:5678
        restart: on-failure

    celery:
        build:
            context: ./backend
            dockerfile: celeryworker.dockerfile
            target: prod
            args:
              GIT_TOKEN_PEDESIS: $GIT_TOKEN_PEDESIS
        depends_on:
            redis:
              condition: service_started
            rabbitmq:
              condition: service_started
            db:
              condition: service_started
        env_file:
            - .env
        environment:
            - REDIS_HOST=redis
            - RABBITMQ_HOST=rabbitmq
            - POSTGRES_HOST=db
            - C_FORCE_ROOT=true
        ports:
            - 5679:5679
        restart: always

    flower:
        image: mher/flower
        env_file:
            - .env
        depends_on:
            celery:
              condition: service_started

volumes:
    data:
      driver: local
